const val releaseUser = "hendraanggrian"
const val releaseGroup = "com.$releaseUser"
const val releaseArtifact = "pikasso"
const val releaseVersion = "0.1"
const val releaseDesc = "Kotlin extensions for Picasso image loader"
const val releaseWeb = "https://github.com/$releaseUser/$releaseArtifact"